In [2]:
pip install selenium webdriver-manager pandas

Note: you may need to restart the kernel to use updated packages.
Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting certifi>=2026.1.4 (from selenium)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting typing_extensions<5.0,>=4.15.0 (from selenium)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: requests in c:\anaconda3\lib\site-packages (from webdriver-manager) (2.32.2)
Requirement already satisfied: python-dotenv in c:\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: packaging in c:\anaconda3\lib\site-packages (from webdriver-manager) (23.2)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: sortedcontainers in c:\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.7)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.16.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: pycparser in c:\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.21)
Collecting h11<1,>=0.16.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.5 MB 42.3 MB/s eta 0:00:01
   ---------------- ----------------------- 4.0/9.5 MB 50.7 MB/s eta 0:00:01
   ---------------------------- ----------- 6.8/9.5 MB 54.6 MB/s eta 0:00:01
   ---------------------------------------  9.5/9.5 MB 61.0 MB/s eta 0:00:01
   ---------------------------------------  9.5/9.5 MB 61.0 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 43.7 MB/s eta 0:00:00
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ------------- -------------------------- 3.2/9.7 MB 103.7 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.7 MB 53.6 MB/s eta 0:00:01
   ------------------------------- -------- 7.8/9.7 MB 61.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 62.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 62.4 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 44.4 MB/s eta 0:00:00
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
   ---------------------------------------- 0.0/153.7 kB ? eta -:--:--
   ---------------------------------------- 153.7/153.7 kB 4.6 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.3 MB 64.6 MB/s eta 0:00:01
   --- ------------------------------------ 1.0/12.3 MB 64.6 MB/s eta 0:00:01
   --- ------------------------------------ 1.0/12.3 MB 64.6 MB/s eta 0:00:01
   ------------- -------------------------- 4.2/12.3 MB 24.6 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 41.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 81.8 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 81.8 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 46.9 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ---------------------------------------- 0.0/510.3 kB ? eta -:--:--
   --------------------------------------- 510.3/510.3 kB 31.3 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ---------------------------------------- 0.0/44.6 kB ? eta -:--:--
   ---------------------------------------- 44.6/44.6 kB 2.1 MB/s eta 0:00:00
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ---------------------------------------- 0.0/131.6 kB ? eta -:--:--
   ---------------------------------------- 131.6/131.6 kB 3.8 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
   ---------------------------------------- 0.0/348.5 kB ? eta -:--:--
   --------------------------------------- 348.5/348.5 kB 10.9 MB/s eta 0:00:00
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
   ---------------------------------------- 0.0/67.5 kB ? eta -:--:--
   ---------------------------------------- 67.5/67.5 kB 1.8 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: urllib3, tzdata, typing_extensions, numpy, h11, certifi, attrs, wsproto, pandas, outcome, webdriver-manager, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.2
    Uninstalling urllib3-2.2.2:
      Successfully uninstalled urllib3-2.2.2
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.11.0
    Uninstalling typing_extensions-4.11.0:
      Successfully uninstalled typing_extensions-4.11.0
  Attempting uninstall: h11
    Found existing installation: h11 0.14.0
    Uninstalling h11-0.14.0:
      Successfully uninstalled h11-0.14.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2024.8.30
    Uninstalling certifi-2024.8.30:
      Successfully uninstalled certifi-2024.8.30
  Attempting uninstall: attrs
    Found existing installation: attrs 23.1.0
    Uninstalling attrs-23.1.0:
      Successfully uninstalled attrs-23.1.0
Successfully installed attrs-26.1.0 certifi-2026.2.25 h11-0.16.0 numpy-2.4.4 outcome-1.3.0.post0 pandas-3.0.1 selenium-4.41.0 trio-0.33.0 trio-websocket-0.12.2 typing_extensions-4.15.0 tzdata-2025.3 urllib3-2.6.3 webdriver-manager-4.0.2 wsproto-1.3.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
httpcore 1.0.2 requires h11<0.15,>=0.13, but you have h11 0.16.0 which is incompatible.

In [22]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.mobilelegends.com/rank")

time.sleep(7)

# 모든 row 가져오기
rows = driver.find_elements(By.CSS_SELECTOR, ".mt-list-layout .mt-list-item")

print("row 개수:", len(rows))  # 확인용

data = []

for row in rows:
    try:
        hero = row.find_element(By.CSS_SELECTOR, ".mt-2693412 span").text
        pick_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684925 span").text
        win_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684926 span").text
        ban_rate = row.find_element(By.CSS_SELECTOR, ".mt-2687632 span").text

        data.append({
            "hero": hero,
            "pick_rate": pick_rate,
            "win_rate": win_rate,
            "ban_rate": ban_rate
        })
    except Exception as e:
        # 일부 row는 구조 다를 수 있음 → 무시
        continue

driver.quit()

df = pd.DataFrame(data)
df.head()

row 개수: 120

     hero pick_rate win_rate ban_rate
0   Masha     0.12%   56.75%    0.40%
1  Lolita     0.16%   56.21%    1.61%
2    Gloo     0.60%   55.98%   74.27%
3    Kaja     0.27%   55.36%    3.05%
4    Gord     0.77%   54.31%    0.61%

In [60]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.mobilelegends.com/rank")
time.sleep(7)

# ✅ Step 1: ALL 드롭다운 클릭
dropdowns = driver.find_elements(By.XPATH, "//div[contains(@class,'mt-dropdown')]")
all_dropdown = dropdowns[4]
driver.execute_script("arguments[0].click();", all_dropdown)
print("ALL 드롭다운 클릭 성공")
time.sleep(2)

# ✅ Step 2: 드롭다운 리스트에서 'Mythical Glory+' span 찾아서 클릭
dropdown_list = dropdowns[5]
option = dropdown_list.find_element(
    By.XPATH, ".//span[text()='Mythical Glory+']"
)
driver.execute_script("arguments[0].click();", option)
print("Mythical Glory+ 선택 완료")
time.sleep(5)  # 데이터 갱신 대기

# ✅ Step 3: 데이터 수집
rows = driver.find_elements(By.CSS_SELECTOR, ".mt-list-layout .mt-list-item")
print("row 개수:", len(rows))

data = []
for row in rows:
    try:
        hero = row.find_element(By.CSS_SELECTOR, ".mt-2693412 span").text
        pick_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684925 span").text
        win_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684926 span").text
        ban_rate = row.find_element(By.CSS_SELECTOR, ".mt-2687632 span").text
        data.append({
            "hero": hero,
            "pick_rate": pick_rate,
            "win_rate": win_rate,
            "ban_rate": ban_rate
        })
    except:
        continue

driver.quit()

df = pd.DataFrame(data)
print(df)

ALL 드롭다운 클릭 성공
Mythical Glory+ 선택 완료
row 개수: 120
        hero pick_rate win_rate ban_rate
0      Masha     0.43%   58.13%    2.68%
1     Diggie     0.43%   56.50%   24.68%
2       Kaja     0.92%   55.78%   22.38%
3     Lolita     0.23%   55.22%    0.91%
4     Zhuxin     1.28%   55.17%   72.77%
5   Fredrinn     1.42%   54.18%   52.18%
6       Gord     0.65%   54.09%    0.11%
7     Floryn     2.00%   54.03%   16.54%
8     Odette     0.75%   53.88%    0.98%
9      Baxia     0.35%   53.85%    1.14%
10    Khufra     0.64%   53.66%    2.27%
11  Minotaur     0.95%   53.59%    9.08%
12     Estes     0.86%   53.45%   48.54%
13     Natan     1.61%   53.36%   12.45%
14    Harley     1.92%   53.24%   11.18%
15       Yve     0.41%   53.19%    0.25%
16   Faramis     0.24%   53.13%    0.36%
17   Leomord     1.65%   53.11%   22.90%
18    Kadita     1.51%   53.02%   18.31%
19     Freya     1.30%   52.67%   72.73%

In [62]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.mobilelegends.com/rank")
time.sleep(7)

# ✅ Step 1: ALL 드롭다운 클릭
dropdowns = driver.find_elements(By.XPATH, "//div[contains(@class,'mt-dropdown')]")
all_dropdown = dropdowns[4]
driver.execute_script("arguments[0].click();", all_dropdown)
print("ALL 드롭다운 클릭 성공")
time.sleep(2)

# ✅ Step 2: Mythical Glory+ 선택
dropdown_list = dropdowns[5]
option = dropdown_list.find_element(By.XPATH, ".//span[text()='Mythical Glory+']")
driver.execute_script("arguments[0].click();", option)
print("Mythical Glory+ 선택 완료")
time.sleep(5)

# ✅ Step 3: 스크롤 내리면서 전체 데이터 로드
last_count = 0
while True:
    # 현재 로드된 row 수 확인
    rows = driver.find_elements(By.CSS_SELECTOR, ".mt-list-layout .mt-list-item")
    current_count = len(rows)
    print(f"현재 row 수: {current_count}")

    # 마지막 row로 스크롤
    driver.execute_script("arguments[0].scrollIntoView();", rows[-1])
    time.sleep(2)  # 추가 데이터 로딩 대기

    # 더 이상 늘어나지 않으면 종료
    if current_count == last_count:
        print("모든 데이터 로드 완료")
        break
    last_count = current_count

# ✅ Step 4: 전체 데이터 수집
rows = driver.find_elements(By.CSS_SELECTOR, ".mt-list-layout .mt-list-item")
print(f"최종 row 개수: {len(rows)}")

data = []
for row in rows:
    try:
        hero = row.find_element(By.CSS_SELECTOR, ".mt-2693412 span").text
        pick_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684925 span").text
        win_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684926 span").text
        ban_rate = row.find_element(By.CSS_SELECTOR, ".mt-2687632 span").text
        data.append({
            "hero": hero,
            "pick_rate": pick_rate,
            "win_rate": win_rate,
            "ban_rate": ban_rate
        })
    except:
        continue

driver.quit()

df = pd.DataFrame(data)
print(f"수집된 데이터: {len(df)}행")
print(df)

ALL 드롭다운 클릭 성공
Mythical Glory+ 선택 완료
현재 row 수: 120
현재 row 수: 240
현재 row 수: 360
현재 row 수: 480
현재 row 수: 600
현재 row 수: 720
현재 row 수: 792
현재 row 수: 792
모든 데이터 로드 완료
최종 row 개수: 792
수집된 데이터: 132행
               hero pick_rate win_rate ban_rate
0             Masha     0.43%   58.13%    2.68%
1            Diggie     0.43%   56.50%   24.68%
2              Kaja     0.92%   55.78%   22.38%
3            Lolita     0.23%   55.22%    0.91%
4            Zhuxin     1.28%   55.17%   72.77%
5          Fredrinn     1.42%   54.18%   52.18%
6              Gord     0.65%   54.09%    0.11%
7            Floryn     2.00%   54.03%   16.54%
8            Odette     0.75%   53.88%    0.98%
9             Baxia     0.35%   53.85%    1.14%
10           Khufra     0.64%   53.66%    2.27%
11         Minotaur     0.95%   53.59%    9.08%
12            Estes     0.86%   53.45%   48.54%
13            Natan     1.61%   53.36%   12.45%
14           Harley     1.92%   53.24%   11.18%
15              Yve     0.41%   53.19%    0.25%
16          Faramis     0.24%   53.13%    0.36%
17          Leomord     1.65%   53.11%   22.90%
18           Kadita     1.51%   53.02%   18.31%
19            Freya     1.30%   52.67%   72.73%
20             Chip     0.11%   52.57%    0.47%
21        Benedetta     0.91%   52.41%    1.77%
22             Ruby     0.81%   52.40%    0.34%
23           Marcel     0.47%   52.10%   67.36%
24           Uranus     0.54%   52.01%    0.44%
25          Phoveus     0.86%   51.84%    1.59%
26            Aamon     0.64%   51.84%    6.88%
27          Khaleed     0.66%   51.80%    0.49%
28            Hilda     0.83%   51.78%   20.14%
29           Hanabi     1.69%   51.73%    6.92%
30          Melissa     0.38%   51.70%    0.14%
31           Arlott     0.79%   51.60%    0.60%
32          Irithel     0.43%   51.59%    0.05%
33        Guinevere     1.86%   51.45%   53.67%
34           Moskov     1.36%   51.45%    0.28%
35          Obsidia     1.21%   51.19%    1.66%
36           Karrie     1.71%   51.11%   36.37%
37             Ixia     0.68%   51.10%    2.36%
38           Zetian     2.33%   50.95%   10.35%
39            Suyou     3.09%   50.95%   12.16%
40         Yu Zhong     1.26%   50.95%    2.01%
41            Lukas     0.70%   50.85%    0.68%
42            Valir     0.72%   50.81%    0.79%
43            Nolan     0.47%   50.62%    0.17%
44          Rafaela     0.18%   50.50%    0.24%
45             Miya     0.87%   50.45%    0.82%
46             Sora     1.47%   50.43%   82.10%
47          Natalia     0.21%   50.38%    0.49%
48              Joy     0.67%   50.35%    0.93%
49          Alucard     0.47%   50.23%    0.20%
50         Silvanna     0.55%   50.14%    0.22%
51           Kagura     1.27%   50.12%    0.89%
52            Argus     0.19%   50.08%    0.10%
53       Minsitthar     0.98%   50.04%   16.33%
54        Valentina     0.60%   50.01%    0.99%
55            Brody     0.68%   49.89%    0.18%
56            Grock     1.21%   49.85%   15.35%
57           Badang     1.11%   49.84%    1.63%
58          Cyclops     0.54%   49.84%    0.09%
59            Zhask     0.21%   49.83%    0.04%
60             Akai     0.55%   49.81%    0.72%
61            Alice     1.30%   49.75%   17.93%
62            Clint     0.92%   49.75%    0.47%
63          Beatrix     1.08%   49.62%    0.77%
64           Harith     0.45%   49.61%    0.12%
65             Gloo     0.87%   49.59%   58.19%
66           Eudora     0.36%   49.43%    0.18%
67           Pharsa     0.69%   49.32%    0.09%
68      Yi Sun-shin     2.79%   49.25%   32.13%
69        Lapu-Lapu     1.12%   49.21%    0.29%
70            Edith     0.15%   49.19%    0.04%
71           Gusion     1.95%   49.16%   14.31%
72              Sun     1.11%   49.11%    3.70%
73            Lunox     0.80%   49.11%    0.23%
74          Helcurt     0.71%   49.08%   30.62%
75   Popol and Kupa     0.15%   49.06%    0.04%
76           Claude     1.24%   48.94%    0.33%
77            Bruno     0.21%   48.91%    0.04%
78           Aldous     0.19%   48.84%    0.12%
79           Thamuz     0.61%   48.56%    0.66%
80            Kimmy     1.20%   48.53%    1.25%
81          Jawhead     0.21%   48.30%    0.05%
82          Terizla     0.31%   48.25%    0.04%
83          Johnson     0.40%   48.18%    0.64%
84           Selena     0.81%   48.10%    0.36%
85         Cecilion     0.59%   47.95%    0.07%
86         Carmilla     0.60%   47.93%    0.32%
87              Yin     0.26%   47.91%    0.15%
88            Saber     0.32%   47.82%    1.09%
89             Vale     0.23%   47.79%    0.03%
90           Angela     1.91%   47.75%    7.34%
91           Xavier     0.64%   47.57%    0.06%
92           Vexana     0.96%   47.54%    0.18%
93          Novaria     0.79%   47.52%    0.27%
94            Kalea     0.31%   47.48%    0.85%
95           Julian     1.08%   47.43%    0.40%
96          Paquito     0.41%   47.41%    0.07%
97           Barats     0.10%   47.38%    0.03%
98            Atlas     0.30%   47.25%    0.25%
99          Granger     1.95%   47.25%    1.71%
100          Lesley     1.10%   47.19%    1.99%
101          Aurora     0.16%   47.05%    0.01%
102        Hayabusa     0.98%   47.02%    1.12%
103            Bane     0.20%   46.94%    0.05%
104          Martis     0.33%   46.59%    0.07%
105           Hylos     0.31%   46.40%    0.08%
106          Karina     0.26%   46.38%    0.20%
107          Wanwan     0.14%   46.29%    0.04%
108       Gatotkaca     0.34%   46.13%    0.11%
109            Cici     0.40%   46.07%    0.11%
110           Lylia     0.81%   46.06%    0.19%
111            Chou     0.83%   45.90%    0.51%
112        Mathilda     0.31%   45.77%    0.35%
113         Chang'e     0.54%   45.49%    0.07%
114           Fanny     0.95%   45.46%    6.77%
115          Luo Yi     0.18%   45.38%    0.03%
116         Tigreal     1.18%   45.33%    2.10%
117           Hanzo     0.32%   45.27%    2.08%
118        Belerick     0.43%   44.91%    0.41%
119          X.Borg     0.46%   44.90%    0.92%
120           Layla     0.23%   44.32%    0.27%
121            Nana     0.44%   44.26%    0.21%
122           Aulus     0.05%   44.24%    0.04%
123           Roger     0.20%   43.93%    0.04%
124            Ling     0.21%   43.37%    0.06%
125          Zilong     0.22%   43.28%    0.17%
126          Franco     0.98%   43.13%    4.81%
127       Esmeralda     0.45%   42.38%    0.18%
128         Dyrroth     0.13%   42.33%    0.05%
129        Lancelot     0.61%   41.64%    0.40%
130           Alpha     0.21%   39.98%    0.03%
131         Balmond     0.08%   35.68%    0.13%

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.mobilelegends.com/rank")
time.sleep(7)

# ✅ Step 1: ALL 드롭다운 클릭
dropdowns = driver.find_elements(By.XPATH, "//div[contains(@class,'mt-dropdown')]")
all_dropdown = dropdowns[4]
driver.execute_script("arguments[0].click();", all_dropdown)
time.sleep(2)

# ✅ Step 2: Mythical Glory+ 선택
dropdown_list = dropdowns[5]
option = dropdown_list.find_element(By.XPATH, ".//span[text()='Mythical Glory+']")
driver.execute_script("arguments[0].click();", option)
time.sleep(5)

# ✅ Step 3: 스크롤로 전체 데이터 로드
last_count = 0
while True:
    rows = driver.find_elements(By.CSS_SELECTOR, ".mt-list-layout .mt-list-item")
    current_count = len(rows)
    print(f"현재 row 수: {current_count}")
    driver.execute_script("arguments[0].scrollIntoView();", rows[-1])
    time.sleep(2)
    if current_count == last_count:
        print("모든 데이터 로드 완료")
        break
    last_count = current_count

# ✅ Step 4: 데이터 수집
rows = driver.find_elements(By.CSS_SELECTOR, ".mt-list-layout .mt-list-item")
data = []
for row in rows:
    try:
        hero = row.find_element(By.CSS_SELECTOR, ".mt-2693412 span").text
        pick_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684925 span").text
        win_rate = row.find_element(By.CSS_SELECTOR, ".mt-2684926 span").text
        ban_rate = row.find_element(By.CSS_SELECTOR, ".mt-2687632 span").text
        data.append({
            "hero": hero,
            "pick_rate": pick_rate,
            "win_rate": win_rate,
            "ban_rate": ban_rate
        })
    except:
        continue

driver.quit()

# ✅ Step 5: win_rate + ban_rate 합산 컬럼 추가 후 내림차순 정렬
df = pd.DataFrame(data)

df["win_rate_f"] = df["win_rate"].str.replace("%", "").astype(float)
df["ban_rate_f"] = df["ban_rate"].str.replace("%", "").astype(float)

# 픽률 + 밴률도 추가
df["pick_rate_f"] = df["pick_rate"].str.replace("%", "").astype(float)
df["pick_ban_sum_f"] = df["pick_rate_f"] + df["ban_rate_f"]
df["pick_ban_sum"] = df["pick_ban_sum_f"].map(lambda x: f"{x:.2f}%")

df["win_ban_sum_f"] = df["win_rate_f"] + df["ban_rate_f"]

df["win_ban_sum"] = df["win_ban_sum_f"].map(lambda x: f"{x:.2f}%")

# 정렬 어떤 컬럼으로 어떻게 할지 정하기.
df = df.sort_values("pick_ban_sum_f", ascending=False).reset_index(drop=True)

df = df.drop(columns=["win_rate_f", "ban_rate_f", "win_ban_sum_f"])

# 5개 행만 보여주는 게 아닌 전체 행 보여주기
pd.set_option('display.max_rows', None)
# print(df)
df

현재 row 수: 120
현재 row 수: 240
현재 row 수: 360
현재 row 수: 480
현재 row 수: 600
현재 row 수: 720
현재 row 수: 792
현재 row 수: 792
모든 데이터 로드 완료

,hero,pick_rate,win_rate,ban_rate,pick_rate_f,pick_ban_sum_f,pick_ban_sum,win_ban_sum
0,Sora,1.33%,51.23%,85.82%,1.33,87.15,87.15%,137.05%
1,Gloo,0.84%,50.94%,69.74%,0.84,70.58,70.58%,120.68%
2,Marcel,0.42%,53.84%,69.20%,0.42,69.62,69.62%,123.04%
3,Freya,1.26%,52.38%,65.80%,1.26,67.06,67.06%,118.18%
4,Zhuxin,1.20%,54.31%,61.20%,1.20,62.40,62.40%,115.51%
5,Guinevere,1.80%,51.74%,53.33%,1.80,55.13,55.13%,105.07%
6,Fredrinn,1.31%,53.56%,43.61%,1.31,44.92,44.92%,97.17%
7,Estes,0.81%,53.47%,43.88%,0.81,44.69,44.69%,97.35%
8,Harley,2.43%,53.86%,39.43%,2.43,41.86,41.86%,93.29%
9,Helcurt,0.74%,49.57%,33.27%,0.74,34.01,34.01%,82.84%
10,Karrie,1.76%,52.08%,31.37%,1.76,33.13,33.13%,83.45%
11,Yi Sun-shin,2.56%,48.80%,28.60%,2.56,31.16,31.16%,77.40%
12,Hilda,0.88%,51.79%,24.02%,0.88,24.90,24.90%,75.81%
13,Minsitthar,1.01%,50.72%,20.67%,1.01,21.68,21.68%,71.39%
14,Kaja,0.82%,56.12%,20.42%,0.82,21.24,21.24%,76.54%
15,Alice,1.23%,50.44%,18.28%,1.23,19.51,19.51%,68.72%
16,Floryn,1.77%,54.06%,17.08%,1.77,18.85,18.85%,71.14%
17,Diggie,0.36%,56.25%,17.90%,0.36,18.26,18.26%,74.15%
18,Kadita,1.39%,52.58%,16.26%,1.39,17.65,17.65%,68.84%
19,Zetian,3.07%,51.18%,14.55%,3.07,17.62,17.62%,65.73%
20,Leomord,1.31%,52.89%,16.31%,1.31,17.62,17.62%,69.20%
21,Suyou,3.00%,51.17%,14.27%,3.00,17.27,17.27%,65.44%
22,Gusion,1.90%,49.46%,14.14%,1.90,16.04,16.04%,63.60%
23,Grock,1.22%,48.86%,12.75%,1.22,13.97,13.97%,61.61%
24,Angela,1.85%,48.04%,7.47%,1.85,9.32,9.32%,55.51%
25,Hanabi,1.93%,52.42%,7.04%,1.93,8.97,8.97%,59.46%
26,Natan,1.25%,53.46%,7.26%,1.25,8.51,8.51%,60.72%
27,Sun,1.31%,50.18%,6.34%,1.31,7.65,7.65%,56.52%
28,Minotaur,0.83%,53.32%,6.64%,0.83,7.47,7.47%,59.96%
29,Franco,1.05%,43.58%,5.17%,1.05,6.22,6.22%,48.75%
30,Aamon,0.60%,51.34%,5.51%,0.60,6.11,6.11%,56.85%
31,Fanny,0.84%,44.39%,4.94%,0.84,5.78,5.78%,49.33%
32,Tigreal,1.35%,45.47%,2.69%,1.35,4.04,4.04%,48.16%
33,Lesley,1.26%,47.62%,2.34%,1.26,3.60,3.60%,49.96%
34,Granger,2.17%,44.86%,1.40%,2.17,3.57,3.57%,46.26%
35,Yu Zhong,1.26%,50.45%,1.67%,1.26,2.93,2.93%,52.12%
36,Badang,1.14%,50.45%,1.71%,1.14,2.85,2.85%,52.16%
37,Hanzo,0.33%,46.98%,2.47%,0.33,2.80,2.80%,49.45%
38,Obsidia,1.07%,51.47%,1.51%,1.07,2.58,2.58%,52.98%
39,Phoveus,0.86%,52.67%,1.64%,0.86,2.50,2.50%,54.31%
40,Khufra,0.59%,53.61%,1.89%,0.59,2.48,2.48%,55.50%
41,Benedetta,0.85%,52.27%,1.59%,0.85,2.44,2.44%,53.86%
42,Hayabusa,1.02%,47.28%,1.26%,1.02,2.28,2.28%,48.54%
43,Saber,0.40%,48.45%,1.88%,0.40,2.28,2.28%,50.33%
44,Masha,0.35%,57.68%,1.81%,0.35,2.16,2.16%,59.49%
45,Kimmy,1.09%,48.80%,1.05%,1.09,2.14,2.14%,49.85%
46,Ixia,0.63%,50.50%,1.34%,0.63,1.97,1.97%,51.84%
47,Miya,0.92%,51.79%,1.04%,0.92,1.96,1.96%,52.83%
48,Kagura,1.11%,50.28%,0.73%,1.11,1.84,1.84%,51.01%
49,Julian,1.16%,47.72%,0.58%,1.16,1.74,1.74%,48.30%
50,X.Borg,0.53%,45.47%,1.17%,0.53,1.70,1.70%,46.64%
51,Valir,0.72%,50.98%,0.88%,0.72,1.60,1.60%,51.86%
52,Claude,1.27%,49.41%,0.29%,1.27,1.56,1.56%,49.70%
53,Moskov,1.31%,52.15%,0.24%,1.31,1.55,1.55%,52.39%
54,Valentina,0.52%,47.88%,1.00%,0.52,1.52,1.52%,48.88%
55,Chou,0.82%,45.38%,0.63%,0.82,1.45,1.45%,46.01%
56,Clint,0.94%,50.91%,0.49%,0.94,1.43,1.43%,51.40%
57,Beatrix,0.94%,49.55%,0.49%,0.94,1.43,1.43%,50.04%
58,Akai,0.57%,49.43%,0.84%,0.57,1.41,1.41%,50.27%
59,Lapu-Lapu,1.03%,48.96%,0.29%,1.03,1.32,1.32%,49.25%
60,Joy,0.57%,50.45%,0.74%,0.57,1.31,1.31%,51.19%
61,Vexana,1.05%,48.57%,0.25%,1.05,1.30,1.30%,48.82%
62,Selena,0.83%,47.75%,0.45%,0.83,1.28,1.28%,48.20%
63,Thamuz,0.63%,49.49%,0.63%,0.63,1.26,1.26%,50.12%
64,Arlott,0.73%,50.83%,0.51%,0.73,1.24,1.24%,51.34%
65,Odette,0.67%,53.47%,0.57%,0.67,1.24,1.24%,54.04%
66,Khaleed,0.64%,52.17%,0.60%,0.64,1.24,1.24%,52.77%
67,Lukas,0.64%,50.27%,0.59%,0.64,1.23,1.23%,50.86%
68,Novaria,0.81%,47.45%,0.34%,0.81,1.15,1.15%,47.79%
69,Belerick,0.54%,46.55%,0.59%,0.54,1.13,1.13%,47.14%
70,Baxia,0.29%,51.76%,0.84%,0.29,1.13,1.13%,52.60%
71,Lolita,0.23%,55.16%,0.89%,0.23,1.12,1.12%,56.05%
72,Kalea,0.33%,47.11%,0.78%,0.33,1.11,1.11%,47.89%
73,Uranus,0.60%,51.62%,0.50%,0.60,1.10,1.10%,52.12%
74,Ruby,0.78%,52.07%,0.26%,0.78,1.04,1.04%,52.33%
75,Silvanna,0.67%,50.94%,0.37%,0.67,1.04,1.04%,51.31%
76,Lylia,0.79%,46.92%,0.21%,0.79,1.00,1.00%,47.13%
77,Lancelot,0.62%,41.99%,0.35%,0.62,0.97,0.97%,42.34%
78,Lunox,0.74%,48.66%,0.22%,0.74,0.96,0.96%,48.88%
79,Carmilla,0.62%,48.76%,0.34%,0.62,0.96,0.96%,49.10%
80,Johnson,0.41%,47.76%,0.54%,0.41,0.95,0.95%,48.30%
81,Natalia,0.23%,50.12%,0.70%,0.23,0.93,0.93%,50.82%
82,Brody,0.71%,50.96%,0.19%,0.71,0.90,0.90%,51.15%
83,Gord,0.68%,54.29%,0.15%,0.68,0.83,0.83%,54.44%
84,Nana,0.52%,44.74%,0.28%,0.52,0.80,0.80%,45.02%
85,Pharsa,0.64%,48.90%,0.08%,0.64,0.72,0.72%,48.98%
86,Atlas,0.36%,48.74%,0.35%,0.36,0.71,0.71%,49.09%
87,Eudora,0.40%,48.84%,0.29%,0.40,0.69,0.69%,49.13%
88,Cyclops,0.58%,49.61%,0.11%,0.58,0.69,0.69%,49.72%
89,Esmeralda,0.47%,41.99%,0.21%,0.47,0.68,0.68%,42.20%
90,Cecilion,0.59%,48.34%,0.07%,0.59,0.66,0.66%,48.41%
91,Xavier,0.60%,48.71%,0.06%,0.60,0.66,0.66%,48.77%
92,Chang'e,0.56%,46.33%,0.09%,0.56,0.65,0.65%,46.42%
93,Faramis,0.21%,52.50%,0.44%,0.21,0.65,0.65%,52.94%
94,Alucard,0.47%,49.92%,0.17%,0.47,0.64,0.64%,50.09%
95,Harith,0.49%,47.92%,0.12%,0.49,0.61,0.61%,48.04%
96,Layla,0.32%,45.14%,0.29%,0.32,0.61,0.61%,45.43%
97,Cici,0.41%,46.18%,0.15%,0.41,0.56,0.56%,46.33%
98,Mathilda,0.27%,45.84%,0.28%,0.27,0.55,0.55%,46.12%
99,Irithel,0.46%,52.23%,0.07%,0.46,0.53,0.53%,52.30%
100,Melissa,0.37%,51.96%,0.16%,0.37,0.53,0.53%,52.12%
101,Karina,0.29%,45.06%,0.23%,0.29,0.52,0.52%,45.29%
102,Chip,0.10%,51.21%,0.42%,0.10,0.52,0.52%,51.63%
103,Nolan,0.39%,50.05%,0.12%,0.39,0.51,0.51%,50.17%
104,Rafaela,0.20%,50.77%,0.31%,0.20,0.51,0.51%,51.08%
105,Gatotkaca,0.38%,46.54%,0.11%,0.38,0.49,0.49%,46.65%
106,Paquito,0.39%,46.89%,0.09%,0.39,0.48,0.48%,46.98%
107,Yin,0.26%,48.01%,0.18%,0.26,0.44,0.44%,48.19%
108,Zilong,0.25%,44.78%,0.19%,0.25,0.44,0.44%,44.97%
109,Hylos,0.33%,46.97%,0.10%,0.33,0.43,0.43%,47.07%
110,Yve,0.29%,52.50%,0.14%,0.29,0.43,0.43%,52.64%
111,Ling,0.34%,44.35%,0.08%,0.34,0.42,0.42%,44.43%
112,Martis,0.33%,46.51%,0.08%,0.33,0.41,0.41%,46.59%
113,Terizla,0.33%,48.44%,0.05%,0.33,0.38,0.38%,48.49%
114,Jawhead,0.25%,48.38%,0.06%,0.25,0.31,0.31%,48.44%
115,Aldous,0.20%,49.55%,0.11%,0.20,0.31,0.31%,49.66%
116,Alpha,0.27%,41.45%,0.04%,0.27,0.31,0.31%,41.49%
117,Argus,0.19%,50.28%,0.11%,0.19,0.30,0.30%,50.39%
118,Vale,0.26%,48.26%,0.03%,0.26,0.29,0.29%,48.29%
119,Zhask,0.24%,51.08%,0.05%,0.24,0.29,0.29%,51.13%
120,Roger,0.24%,46.12%,0.03%,0.24,0.27,0.27%,46.15%
121,Bane,0.21%,48.18%,0.05%,0.21,0.26,0.26%,48.23%
122,Bruno,0.21%,47.75%,0.03%,0.21,0.24,0.24%,47.78%
123,Popol and Kupa,0.16%,50.14%,0.05%,0.16,0.21,0.21%,50.19%
124,Edith,0.17%,49.24%,0.04%,0.17,0.21,0.21%,49.28%
125,Luo Yi,0.18%,46.40%,0.03%,0.18,0.21,0.21%,46.43%
126,Balmond,0.09%,37.54%,0.12%,0.09,0.21,0.21%,37.66%
127,Wanwan,0.15%,45.27%,0.05%,0.15,0.20,0.20%,45.32%
128,Dyrroth,0.14%,41.66%,0.04%,0.14,0.18,0.18%,41.70%
129,Aurora,0.16%,46.84%,0.02%,0.16,0.18,0.18%,46.86%
130,Barats,0.10%,48.48%,0.03%,0.10,0.13,0.13%,48.51%
131,Aulus,0.06%,47.71%,0.03%,0.06,0.09,0.09%,47.74%

In [3]:
# 기존 print(df) 대신 HTML 파일로 저장
from datetime import datetime

html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>MLBB Mythical Glory+ Stats</title>
    <style>
        body {{ font-family: Arial, sans-serif; padding: 20px; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: center; }}
        th {{ background-color: #4CAF50; color: white; }}
        tr:nth-child(even) {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    <h2>MLBB Mythical Glory+ Hero Stats</h2>
    <p>Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    {df.to_html(index=False)}
</body>
</html>
"""

with open("index.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("index.html 저장 완료")

index.html 저장 완료